services:
  server:
    build: ./server
    container_name: server
    networks:
      smarthome_macvlan:
        ipv4_address: 172.20.0.2
    depends_on:
      - mosquitto
    volumes:
      - server_data:/app/data
    ports:
      - "5001:5000" # Vulnerability 1: Open port accessible without restrictions

  client:
    build: ./client
    container_name: client
    networks:
      smarthome_macvlan:
        ipv4_address: 172.20.0.3
    depends_on:
      - mosquitto
    volumes:
      - client_data:/app/data

  mosquitto:
    build: ./mosquitto
    container_name: mosquitto
    networks:
      smarthome_macvlan:
        ipv4_address: 172.20.0.4
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/mosquitto.conf
      - ./mosquitto/passwordfile:/mosquitto/passwordfile
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    ports:
      - "1883:1883" # Vulnerability 1: Open port accessible without restrictions

#  kali:
#    build: ./kali
#    container_name: kali
#    networks:
#      smarthome_macvlan:
#        ipv4_address: 172.20.0.5
#    volumes:
#      - kali_data:/root/data
#    ports:
#      - "5901:5900" # VNC
#    cap_add:
#      - NET_ADMIN
#      - NET_RAW
#    privileged: true

  api:
    build: ./api
    container_name: api
    env_file: .env
    ports:
      - "8000:8000"
    restart: unless-stopped

networks:
  smarthome_macvlan:
    external: true
    name: smarthome_macvlan

volumes:
  server_data:
  client_data:
  mosquitto_data:
  mosquitto_log:
  kali_data:
